### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by GoHoHa** [alexsocha/luckyblock#1]
Dear Alex,
I tried to do build the luckyblock mod from your code, but both master and mc13.2 fork are failing. I used an fresh install of gradle (version 5.0) on a xubuntu mashine (18.04, kernel 4.15) with java (1.8.0_201). 
The error occurs already at line 10 of build.gradle
I never used gradle before, so I am a little lost where to begin to look for the cause.

> `> gradle build.gradle`
> `FAILURE: Build failed with an exception.`
> `* Where: Build file '/home/jg/git/lucky12/build.gradle' line: 10`
> `* What went wrong: A problem occurred evaluating root project 'lucky12'.`
> `org.gradle.api.internal.TaskOutputsInternal.dir(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskOutputs;`

Did I miss some dependencies?

GoHoHa

**Comment by alexsocha** [comment]
Hi GoHoHa,

Here is a link to the forge docs: [https://mcforge.readthedocs.io/en/latest/gettingstarted/](url)

Basically, you need to run `./gradlew ...` (use `./gradlew tasks` to see all valid tasks). Note that this will only work for master, as mc1.13 is still very much under development.

Hope that helps,
Alex

**Comment by GoHoHa** [comment]
Thank you, this helped me to get started. Issue solved.
