### ISSUE TITLE
Setting doDropsOnCreativeMode=True doesn't do anything.

### ISSUE THREAD

**Issue by KristenStuffs** [alexsocha/luckyblock#10]
When I set doDropsOnCreativeMode=True in the Lucky Block's config\lucky\version-1.16.1-1\properties.txt or in my addon's properties.txt file in Lucky Block for 1.16.1 it does nothing and still requires a Redstone to open in Creative Mode.

I have confirmed this did work in Lucky Block for 1.15.2.

**Comment by alexsocha** [comment]
Thanks, should be fixed in the latest release
