### ISSUE TITLE
Baby #pName Armour Stand doesn't work as intended

### ISSUE THREAD

**Issue by KristenStuffs** [alexsocha/luckyblock#13]
Basically the baby player armour stand is written like this:

`type=entity,ID=armor_stand,NBTTag=(Small=true,NoBasePlate=true,ShowArms=true,RightArm=(id=stone_pickaxe,Count=1),ArmorItems=[(id=leather_boots,Count=1,tag=(display=(color=#randColor))),(id=leather_leggings,Count=1,tag=(display=(color=#randColor))),(id=leather_chestplate,Count=1,tag=(display=(color=#randColor))),(id=player_head,Count=1,tag=(SkullOwner=#pName))],Rotation=[#pYaw+180f,0f],CustomName=#jsonStr(text="Baby #pName"),CustomNameVisible=true)@luck=0
`

According to the way it's written, it should have a stone pickaxe in hand, however no stone pickaxe appears when the baby player spawns, which can be seen in [this image](https://imgur.com/a/KYHM8kY). I am using Lucky Block for 1.16.4-1.

**Comment by alexsocha** [comment]
Fixed in 1.16.4-2; Minecraft changed the NBT format, so that `RightArm`/`LeftArm` is now `HandItems`
