### ISSUE TITLE
Colorful Pole Crash

### ISSUE THREAD

**Issue by KristenStuffs** [alexsocha/luckyblock#14]
The drop known as colorful pole crashes the game when loaded into Minecraft Forge 1.16.4 (any version.) Crash was not present in Lucky Block for 1.16.1. When the world gets relaunched after the crash, the rest of the colorful pole spawns in normally. Crash was replicated by making the colorful pole drop the most common drop in the config file of the Lucky Block mod, but the effect is still the same.

[latest.log](https://github.com/alexsocha/luckyblock/files/5760608/latest.log)
[crash-2021-01-02_12.36.30-server.txt](https://github.com/alexsocha/luckyblock/files/5760609/crash-2021-01-02_12.36.30-server.txt)

**Comment by alexsocha** [comment]
Thanks for spotting this *major* issue. It was actually a problem with the `fill` command which runs before the colorful pole - it's now fixed in 1.16.4-2.
