### ISSUE TITLE
Lucky Block 1.16.4-3 doesn't have a unique config folder

### ISSUE THREAD

**Issue by KristenStuffs** [alexsocha/luckyblock#19]
Lucky Block 1.16.4-3 uses the Lucky Block 1.16.4-2 config folder instead of using a Lucky Block 1.16.4-3 config folder. Due to this, I received a .showupdate.cache file inside of the config folder.

**Comment by alexsocha** [comment]
It should be fixed now - it seams that with gradle, you have to run 'clean' after updating the version number
