### ISSUE TITLE
[1.14.4] LuckyBlocks not dropping anything

### ISSUE THREAD

**Issue by DarkKnightComes** [alexsocha/luckyblock#2]
I had LuckyBlocks for version 1.14.3 and it was working fine. When I updated to 1.14.4, I downloaded a version for 1.14.4 and there are no drops.

**Comment by alexsocha** [comment]
Unfortunately I'm not able to reproduce this behaviour. Maybe try again with the newest forge version? Also note that breaking the block on creative mode should not drop anything by default - try redstone instead.

**Comment by DarkKnightComes** [comment]
Yes, I needed to update Forge. Now it's working fine.
