### ISSUE TITLE
Hero Colour/Boldness Redundancy

### ISSUE THREAD

**Issue by KristenStuffs** [alexsocha/luckyblock#20]
Hero Fishing Rod, Hero Trident, and Hero Crossbow all have $9$l in their name which is redundant as they all have ,color=blue,bold=true which does the exact same thing. I tested the drops without the $9$l by modifying the drops file in the config folder and they work the same.

**Comment by alexsocha** [comment]
Yes, this is a remnant from older versions of Minecraft. I based the new drops on the fished rod, which (accidentally) still had these formatting codes. It's fixed now, and will be published with the next release.
