### ISSUE TITLE
Add addon support to the fabric version

### ISSUE THREAD

**Issue by ExoPlant** [alexsocha/luckyblock#23]
Currently, no addon folder is generated for the user to put addons in to, thus addons do not work, and also, the config folder does not seem to work.

**Comment by ExoPlant** [comment]
it closed itself?

**Comment by ExoPlant** [comment]
hmmmmmm

**Comment by alexsocha** [comment]
hmmmmmmmmmm

**Comment by alexsocha** [comment]
You're right though, the addons folder didn't automatically get created, and I've fixed this now (that said, addons still did work if you made the folder manually)

**Comment by alexsocha** [comment]
Also, by "the config folder does not seem to work", I assume you mean for addons? Because otherwise it seems to be working as expected

**Comment by ExoPlant** [comment]
Okay, so everything is working to do with addons
