### ISSUE TITLE
Wishing well does not generate

### ISSUE THREAD

**Issue by ExoPlant** [alexsocha/luckyblock#24]
Whenever I get the wishing well drop, nothing spawns, at all

**Comment by alexsocha** [comment]
I'm having trouble reproducing this. Could you provide logs (.minecraft/logs/latest.log) and/or the relevant lines in drops.txt?

**Comment by ExoPlant** [comment]
This is on the fabric version btw

**Comment by alexsocha** [comment]
Can't reproduce. Are you sure these are standard wishing wells, and not custom ones (e.g. as part of an addon?)
