### ISSUE TITLE
Question regarding ports

### ISSUE THREAD

**Issue by Draylar** [alexsocha/luckyblock#36]
Hi Alex, hope this finds you well. I could not find another way to contact you, so forgive me for using the issue section here!

I was maintaining a project called _Fabricated Lucky Blocks_ a few months back, which was a fully original/custom version of the Lucky Block mod for Fabric, with the only similarity being the project name. After bickering with a user about the naming of a project (and the legality of it), I decided to rename the project to [Cubi Fortunarum](https://www.curseforge.com/minecraft/mc-mods/cubi-fortunarum). I am curious if you are fine with projects like these, or if you feel it infringes on your creative copyright (in which case I would simply take the project down). 

I have already [read the license on your website](https://www.luckyblockmod.com/info/), and while it does mention add-ons, it does not mention inspired projects such as original ports, minigame renditions, or server-side plugins with the same mechanics, which only uses creative ideas from your project (and **no** re-use of assets or code).

Thanks!

**Comment by alexsocha** [comment]
hey, feel free to shoot me an email at alex@alexsocha.com
