### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by VincentZocker** [alexsocha/luckyblock#4]
Hi, 
I'm a developer, but a Minecraft beginner, so please be patient about my questions.
## What I want
I want to build, deploy start this mod

## What I use
I use [MultiMC 5](https://github.com/MultiMC/MultiMC5/) and was able to add a instance 
![grafik](https://user-images.githubusercontent.com/60041276/72677906-6e20a400-3aa1-11ea-8508-28b7cab87e93.png)

## build
I use IntelliJ community edition and I'm able to build successful.

## deploy
So my main question is, how (and what) to deploy and apply to instance of multiMC5 ?

**Comment by alexsocha** [comment]
If you can build successfully, the mod .jar file is saved in build/dist/. You can install this like any other minecraft forge mod, though I'm not too familiar with how this works in MultiMC
