### ISSUE TITLE
I suggest you update Lucky block for forge 37.0.24 or higher for use/compatibility with personal mod lists. 

### ISSUE THREAD

**Issue by ExiledMiner04** [alexsocha/luckyblock#40]
As far as I know, It will work currently up to 37.0.22, after that version, it throws this error:
Lucky Block (lucky) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

So many mods are not playing well together as they are all with different forge versions for 1.17.1. Its quite a headache.

**Comment by alexsocha** [comment]
Thanks for letting me know, I've put out an update. It's a shame that forge makes so many breaking changes
