### ISSUE TITLE
You may need to update to forge 27.0.32+ due to tool and weapon changes.

### ISSUE THREAD

**Issue by ExiledMiner04** [alexsocha/luckyblock#42]
They changed how tools work so lucky sword and bow could cause this crash:

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'java.util.Set net.minecraft.world.item.ItemStack.getToolTypes()'
Exit Code: -1

I will not use them in the meantime. Vanilla tool drops work fine. I may have to get the word out to the addon publishers as well.

**Comment by alexsocha** [comment]
Thanks, although I've tested against the newest forge and haven't noticed any issues. Have you seen it crash, and do you have the full report handy?

**Comment by ExiledMiner04** [comment]
Just when it crashed with another mod and right clicking anything even with hand caused the cash I thought it was silent gear, but the author examined the full report and said it was pointing to Lucky blocks and quick paths mod. It was this crash. 
[crash-2021-08-12_22.07.08-server.txt](https://github.com/alexsocha/luckyblock/files/6987214/crash-2021-08-12_22.07.08-server.txt)

**Comment by alexsocha** [comment]
Judging by the first line of the error, it's an issue with the quick paths mod:
```
java.lang.NoSuchMethodError: 'java.util.Set net.minecraft.world.item.ItemStack.getToolTypes()'
    at com.natamus.quickpaths.events.PathEvent.onRightClickGrass(PathEvent.java:70) ~[quickpaths_1.17.1-1.7.jar%23112!:1.0] {re:classloading}
```

**Comment by ExiledMiner04** [comment]
Ah ok so not lucky blocks at all. Good.
