### ISSUE TITLE
Hero villager and other custom items even in addons by other authors have hidden enchantments.

### ISSUE THREAD

**Issue by ExiledMiner04** [alexsocha/luckyblock#43]
Forge version: 27.0.33
Lucky Block mod version: 1.17.1-2
Other mods used that may affect it: Wonderful Enchantments

Add-ons used: Strange Lucky Block, Summer Lucky block, Copper lucky block, and Amethyst Lucky Block for 1.17.1 Lucky Block Mod.

using the command: /data get entity @s SelectedItem on the item in question shows the enchantments still on the item and working normally. Enchanted items generated via any vanilla lucky blocks from the main mod, the Hero Villager, or add-on versions will get the new custom enchants from Wonderful Enchantments just fine from looking at the NBT data.

Did you accidentally set HIDE_ENCHANTS tag set to true as well?

**Comment by alexsocha** [comment]
Nice catch! It was an issue with enchantment IDs, fixed in v1.17.1-3
