### ISSUE TITLE
Lucky Blocks not spawning in Minecraft 1.12.2

### ISSUE THREAD

**Issue by Cheeto05** [alexsocha/luckyblock#45]
I am trying to run the Lucky Block mod for version 1.12.2 of Minecraft, however no Lucky Blocks or structures are naturally generating in Creative or Survival. The blocks appear in the block list in creative, and the blocks work in both creative and survival. I am using Forge version 14.23.5.2855 and Lucky Block version 1.12.2-1, downloaded directly from the Lucky Block website. I also ran the mod using Forge 1.7.10 and the 1.7.10 version of the mod and natural spawning occurred. I have attached my server log for the 1.12.2 version of the mod.
[latest.log](https://github.com/alexsocha/luckyblock/files/7525290/latest.log)
 I would appreciate any help anyone can provide :)

**Comment by alexsocha** [comment]
Unfortunately 1.12.2 too outdated to consider investigating this issue :(
