### ISSUE TITLE
Enchantments not showing in 1.18.1

### ISSUE THREAD

**Issue by aAndrew3030** [alexsocha/luckyblock#47]
Items appear to be enchanted, as they have the enchantment glint, but are not actually showing enchantments
1.18.1
Forge 39.0.8
![2021-12-23_16 50 48](https://user-images.githubusercontent.com/84727133/147294759-00db4a87-14ec-4d04-a9e0-9f46b7203ecf.png)
![2021-12-23_16 53 53](https://user-images.githubusercontent.com/84727133/147294774-d4872a1c-6073-4aae-b79d-45909016ca03.png)

**Comment by alexsocha** [comment]
Thanks for finding this! Fixed in 1.18.1-2
