### ISSUE TITLE
[question] can you change to curseforge allowed

### ISSUE THREAD

**Issue by Brandonbr1** [alexsocha/luckyblock#49]
Hi @alexsocha so i have tried to upload a modpack to curseforge.com but when i try and do that it is the luckyblockmod that prevents me from uploading my modpack so can you change the license to make it curseforge allowed? so my and other people modpacks can be uploaded 

![luckyblock](https://user-images.githubusercontent.com/74426342/147934418-43f19751-c613-4d68-a10c-980f384e0140.PNG)

**Comment by alexsocha** [comment]
Sorry, can't do. In general, since public modpacks bypass the original mod's download link, they subtract from the revenue potential of content creators

On a side node, I'm pretty impressed that curseforge enforces these restrictions

**Comment by Brandonbr1** [comment]
> Sorry, can't do. In general, since public modpacks bypass the original mod's download link, they subtract from the revenue potential of content creators
> 
> On a side node, I'm pretty impressed that curseforge enforces these restrictions

ok i will just remove that mod from the modpack  maybe that is an option 

and btw
Cureforge does give you revenue the creators  they get a 70% revenue cut with the ads

and 9minecraft stole your mod btw:
https://www.9minecraft.net/lucky-block-mod/
