### ISSUE TITLE
1.16.5-4 version of mod doesn't work on latest Fabric loader version

### ISSUE THREAD

**Issue by GregoryTheGamer** [alexsocha/luckyblock#52]
Hi I recently updated my 1.16.5 fabric loader version to the latest available (0.12.12-1.16.5) and my game crashes when I do so, I know 1.16.5 is no longer your guy's biggest priority but I would appreciate it if you could fix whatever is causing this crash. I provided my crash log below for reference. I myself can't play on version of Minecraft past 1.16 due to my system not supporting newer Java versions correctly so using the 1.17+ version of the mod is not an option for me. Thanks, Greg
[crash-2022-01-10_14.10.59-client.txt](https://github.com/alexsocha/luckyblock/files/7841620/crash-2022-01-10_14.10.59-client.txt)

**Comment by alexsocha** [comment]
Thanks for letting me know, I've released 1.16.5-5 with support for fabric-loader >= 0.12.0
