### ISSUE TITLE
suggestion:add back the 1.12.2 and 1.8.9 template

### ISSUE THREAD

**Issue by Brandonbr1** [alexsocha/luckyblock#53]
@alexsocha 
Hi PlayerInDistress can you add back the 1.12.2 and 1.8.9 template because that is still a popular Minecraft version for lucky block addons because of loot++ so i can add custom drops

**Comment by alexsocha** [comment]
good suggestion, I plan to improve the template addon version management in the coming months

**Comment by alexsocha** [comment]
Duplicate of https://github.com/alexsocha/luckyblockmod.com/issues/9
