### ISSUE TITLE
doDropsOnCreativeMode=true Doesn't Work in 1.18.1-2 Forge

### ISSUE THREAD

**Issue by KristenStuffs** [alexsocha/luckyblock#55]
Currently using version 1.18.1-2 forge for the lucky block mod and setting doDropsOnCreativeMode=true in properties.txt in the lucky block config folder for 1.18.1-2 doesn't work either. 

Tried it in my own add-on as well by setting doDropsOnCreativeMode=true in the properties.txt file for Lucky Block Pink, doesn't work there either.

**Comment by alexsocha** [comment]
Yes you're right - I've tried to add this back in, but with the latest versions of Forge/Fabric I don't think it's possible to change block break behaviour on creative. Sadly, I'll have to remove this feature and update the docs

**Comment by alexsocha** [comment]
the good news is that I'll replace this with `doDropsOnRightClick=true` in v11
