### ISSUE TITLE
Lucky Block textures no loading without resource pack 1.1.6.5

### ISSUE THREAD

**Issue by Brandonbr1** [alexsocha/luckyblock#56]
my lava lucky block  will not load any textures no matter what it only loads when i have it in a resource pack

lava lucky block:[https://www.curseforge.com/minecraft/customization/lava-lucky-block](https://www.curseforge.com/minecraft/customization/lava-lucky-block)

**Comment by alexsocha** [comment]
I gave it a try (lava-luck-block-version-6.zip) and the textures loaded fine for me, are you still having this issue?

**Comment by alexsocha** [comment]
actually I can reproduce the issue, but only on Windows. I'm pretty sure it's related to https://github.com/alexsocha/luckyblock/issues/65

**Comment by alexsocha** [comment]
it was not related to the other issue, and I'm unsure why it only affected Forge on Windows, but regardless it's fixed in v11
