### ISSUE TITLE
deprecated warning 

### ISSUE THREAD

**Issue by Brandonbr1** [alexsocha/luckyblock#58]
w: /app/fabric/src/main/kotlin/game/LuckyBlock.kt: (57, 15): 'neighborUpdate(BlockState!, World!, BlockPos!, Block!, BlockPos!, Boolean): Unit' is deprecated. Deprecated in Java

> Task :forge:compileKotlin
w: /app/forge/src/main/kotlin/ForgeGameAPI.kt: (453, 81): Type mismatch: inferred type is BlockState? but BlockState was expected
w: /app/forge/src/main/kotlin/ForgeMod.kt: (191, 139): Type mismatch: inferred type is Nothing? but Type<*> was expected
w: /app/forge/src/main/kotlin/game/AddonCraftingRecipe.kt: (71, 69): Type mismatch: inferred type is Nothing? but Level was expected
w: /app/forge/src/main/kotlin/game/LuckyBlock.kt: (52, 15): 'neighborChanged(BlockState!, Level!, BlockPos!, Block!, BlockPos!, Boolean): Unit' is deprecated. Deprecated in Java

> Task :tools:compileKotlin
w: /app/tools/src/main/kotlin/NbtToMcstructure.kt: (44, 9): Variable 'palette' is never used

> Task :bedrock:compileKotlinJs
w: /app/bedrock/src/main/kotlin/BedrockGameAPI.kt: (139, 40): Parameter 'world' is never used
w: /app/bedrock/src/main/kotlin/BedrockGameAPI.kt: (182, 44): Unchecked cast to external interface: PlayerEntity /* = Any */ to MCPlayerEntity
w: /app/bedrock/src/main/kotlin/BedrockGameAPI.kt: (221, 44): Unchecked cast to external interface: World /* = Any */ to MCWorld /* = MCTickWorldComponent */
w: /app/bedrock/src/main/kotlin/BedrockGameAPI.kt: (240, 48): Unchecked cast to external interface: World /* = Any */ to MCWorld /* = MCTickWorldComponent */
w: /app/bedrock/src/main/kotlin/BedrockGameAPI.kt: (325, 54): Unchecked cast to external interface: PlayerEntity /* = Any */ to MCPlayerEntity
w: /app/bedrock/src/main/kotlin/LuckyBlockBedrock.kt: (105, 17): Variable 'block' is never used

**Comment by alexsocha** [comment]
I'll clean those up eventually, but it's safe to ignore for now

**Comment by alexsocha** [comment]
also if I remember correctly, `neighborUpdate` is deprecated but there isn't any good replacement yet, so unfortunately we have to deal with the warning
