### ISSUE TITLE
(1.18 forge) lucky block duplication in luck crafting

### ISSUE THREAD

**Issue by NyanMC** [alexsocha/luckyblock#60]
steps to reproduce:
place a stack of at least 2 lucky blocks and any luck affecting item in the crafting grid
take out the result, you will end up with nearly double the amount of lucky blocks you started with

before (i have 9 lucky blocks and i am about to make them luckier):
![image](https://user-images.githubusercontent.com/44331238/153770100-df242d9f-e620-436d-be39-fc13b54db5c6.png)
after (suddenly i have 17 lucky blocks):
![image](https://user-images.githubusercontent.com/44331238/153770112-8a7abc95-5eb8-4a8f-8c22-f9551a6a0d33.png)

**Comment by alexsocha** [comment]
thanks, great catch! I've fixed this in v10
