### ISSUE TITLE
Lucky block addon can only max out to -15 on 1.1.6.5

### ISSUE THREAD

**Issue by Brandonbr1** [alexsocha/luckyblock#62]
Loader: Forge
Minecraft version  : 1.1.6.5
OS: Windows 10

this issue occurs in Windows

- The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
   - [ ] Unknown
   - [ ] Both

**To Reproduce**
1. Put the lucky block in the player crafting slot
2. add rotten flesh on the remaining slots
3. take it out and put it back in the slot
4. it stays on -15 luck no matter what

@alexsocha 
I was trying to make the lucky block more unlucky but  only got to -15 and it always stayed that way no matter how much rotten flesh I put on it

**Video**
Bug report in vid here:[https://youtu.be/lwOBNbqVwXI?t=647](https://youtu.be/lwOBNbqVwXI?t=647)

timestamp:10:47

**Comment by alexsocha** [comment]
This appears to be working in 1.18.2-12.0, unfortunately I don't have the time to solve issues in older versions

**Comment by Brandonbr1** [comment]
> This appears to be working in 1.18.2-12.0, unfortunately I don't have the time to solve issues in older versions

@alexsocha can you add all the version on branches like 1.1 6.5 1.17 1.12 as branches instead of overriding them in commits so it is easier to fix issues in other versions please😄
