### ISSUE TITLE
Question, is this official?

### ISSUE THREAD

**Issue by KristenStuffs** [alexsocha/luckyblock#63]
I noticed there's a version of the lucky block mod on curseforge which looks similar to the website (https://www.curseforge.com/minecraft/mc-mods/lucky-block) and uses a typical username you go by, although I see no mention of it anywhere outside of curseforge itself. I was wondering if it was you or just another re-upload.

I know there was some talk about curseforge last month on here, which is partially why I'm asking.

**Comment by alexsocha** [comment]
good question, I'm currently having discussions with CurseForge, and will fully release the mod there and update relevant docs in the coming days
