### ISSUE TITLE
Lucky Block Mod Downloads Broken

### ISSUE THREAD

**Issue by NicsGames** [alexsocha/luckyblock#64]
All the downloads on https://www.luckyblockmod.com show 'not found' when trying to download any version from what I am seeing. 

Let me know if you need more information. I apologize if this is the wrong place to reach out. I didn't know how else to contact.

**Comment by Brandonbr1** [comment]
prob this commit:https://github.com/alexsocha/luckyblockmod.com/commit/deaaa7c71a9a11c0ed92c15b67a1e7cd7d1e726b

broke the downloads

**Comment by alexsocha** [comment]
oh no, thanks for noticing, this is now fixed
