### ISSUE TITLE
LuckyBlockMod.com SSL Certificate Expired

### ISSUE THREAD

**Issue by NicsGames** [alexsocha/luckyblock#69]
![image](https://user-images.githubusercontent.com/45801928/156906052-6844af40-f9ca-4fca-847f-d8f170d399b3.png)

It looks like the SSL cert for LuckyBlockMod.com has expired. This causes a warning on Google Chrome and other browsers that can be scary for a lot of users to by-pass. I can help with this if needed. Just let me know!

**Comment by alexsocha** [comment]
Great catch! The ssl certs are set to auto-renew, but there was an issue with the script preventing it from restarting the nginx ingress. Should be fixed now
