### ISSUE TITLE
Question: does addons support .schem?

### ISSUE THREAD

**Issue by Brandonbr1** [alexsocha/luckyblock#70]
Hi so in the lucky block docs the supported formats are .schematic and .luckystruct 

but does it not say it supports .schem the new file that word edit uses to generate structures

and here is a suggestion can you make a tool that converts  .schem/.schematic into .luckystruct

**Comment by alexsocha** [comment]
It supports this schematic format: https://minecraft.fandom.com/wiki/Schematic_file_format, but the blockstate handling is imperfect and it's only there for compatibility. Minecraft structure blocks introduced the `.nbt` format which is preferred, and `.luckystruct` is a custom format similar to `drops.txt`

**Comment by Brandonbr1** [comment]
> It supports this schematic format: https://minecraft.fandom.com/wiki/Schematic_file_format, but the blockstate handling is imperfect and it's only there for compatibility. Minecraft structure blocks introduced the `.nbt` format which is preferred, and `.luckystruct` is a custom format similar to `drops.txt`

ok thank you alexsocha i will change my lucky block structures to .nbt instead to .schematic😊
