### ISSUE TITLE
JSON Language files aren't loaded properly with multiple addons

### ISSUE THREAD

**Issue by XanolResagan** [alexsocha/luckyblock#75]
Using: Lucky Block version 12.0 on Forge 40.0.2

When I'm playing with multiple lucky block addons in the same world, it only loads in the language file of the first addon (regardless if it's in a folder or .zip file), and the others are usually rendered as `block.lucky.[addon]_lucky_block` within all lucky items, as seen here:
(https://cdn.discordapp.com/attachments/442038271778881568/951907681881428018/2022-03-11_19.21.06.png)

In this case, the first loaded block is the amethyst lucky block, which is the only one that does have a proper name:
(https://cdn.discordapp.com/attachments/442038271778881568/951909513768886382/2022-03-11_19.10.24.png)

When I remove the amethyst lucky block from the pack, it will now load the copper lucky block text properly, which it before didn't.
(https://cdn.discordapp.com/attachments/442038271778881568/951909864370761748/2022-03-11_19.29.54.png)

It affects any lucky block addons as of right now, and I have noticed this in both 11.0 and 12.0 versions of the lucky block mod. Not sure if it also affects other installations or if it's on my end, but it is noticble on addons that have different names than the IDs given on plugin_init, more specifically the custom lucky items.

**Comment by alexsocha** [comment]
Also fixed in v13, commit https://github.com/alexsocha/luckyblock/commit/e923ef68709b2e96e786e9caa7575084d5f12bee
