### ISSUE TITLE
Enchantments disappear when upgrading lucky items

### ISSUE THREAD

**Issue by XanolResagan** [alexsocha/luckyblock#79]
- Loader: [Forge]
- Mod version: [1.18.2-12.0]
- OS: [Windows 10]

There occurs to be an inconsistent behaviour when upgrading lucky weapons (such as lucky sword, lucky bow and lucky potion) between 1.8 and 1.18.2 and I feel like mention it here after noticing this issue on a Desert Lucky Block review.

In 1.8, when you upgrade an lucky sword/bow that has enchantments on it already, it will keep the enchantments as it is.
However in 1.18.2, when you upgrade the same lucky sword/bow with lucky items, it will upgrade in luck, but all the
existing enchantments are gone, where the upgraded lucky sword/bow will just act like a normal lucky sword with luck on it.

This also happens with lucky items generated by addons aswell, where the enchantments disappear.
It is a noticable change, as it assumes that the lucky items already have +100 luck in order to put enchantments on it properly,
unlike in older versions.

**Comment by alexsocha** [comment]
Thanks! This has been fixed v13, see commit https://github.com/alexsocha/luckyblock/commit/57cebf31218a82e0c756e3961f46945df23f2f4f
