### ISSUE TITLE
Lucky Block has failed to load correctly

### ISSUE THREAD

**Issue by XanolResagan** [alexsocha/luckyblock#80]
- Loader: Forge 40.0.32
- Mod version1.18.2-13.0
- OS: Windows 10

I updated the lucky block mod to the latest 13.0 version and  as of right now I'm unable to launch the mod properly under default circumstances, even after upgrading the forge version which crashes the game after a short time:

[crash-2022-03-27_12.04.49-fml.txt](https://github.com/alexsocha/luckyblock/files/8357329/crash-2022-03-27_12.04.49-fml.txt)

`[modloading-worker-0/INFO] [mod.lucky.forge.ForgeLuckyRegistry/]: No default resources found. Ignore this in a dev environment.
[modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: lucky, class mod.lucky.forge.ForgeMod
java.lang.reflect.InvocationTargetException: null`

From what I'm getting on the log file is, that the mod fails to generate the files at ".minecraft/config/1.18.2-13.0-forge" which is needed to install the lucky config in there.
I managed to run the mod fine by adding the folder myself, but the contents of the config folder have been not regenerated, leading the default lucky block to not load/drop anything, including default structures that have been reused for various other lucky block addons. lucky-config.zip is also absent in this particular version, which might be why it can't load the settings automatically, and it could lead to further problems given how many addons are dependent on these settings while adding in new drops.

**Comment by alexsocha** [comment]
Glad you caught this so quickly, yes I made some major updates to the build system recently, and as you noticed, it failed to include `lucky-config.zip` in the mod file. Fixed in forge-13.1
