### ISSUE TITLE
Failed to Load Correctly

### ISSUE THREAD

**Issue by scott93063** [alexsocha/luckyblock#89]
I tried to run Minecraft Java 1.19 using CurseForge 41.0.99 and Lucky Block version lucky-block-forge-1.19-13.0.jar, but I receive the following error
![Minecraft_err_LuckyBlock](https://user-images.githubusercontent.com/17748226/179633912-01041f1f-a48a-4ee1-b292-da319a7b3966.PNG)

Crash file:
[LuckyBlockcrash-2022-07-18_18.18.43-fml.txt](https://github.com/alexsocha/luckyblock/files/9136274/LuckyBlockcrash-2022-07-18_18.18.43-fml.txt)

**Comment by alexsocha** [comment]
fixed in 1.19-13.1, which I've just released
