### ISSUE TITLE
Can't find a way to disable new version messages on login

### ISSUE THREAD

**Issue by Jimmio92** [alexsocha/luckyblock#9]
I get reminded there's a new version of Lucky Block for 1.15.2 every time I log in, despite me being restricted to version 1.12.2. Is there a way, maybe hopefully in the configuration already, to disable this welcome message? I'd hate to have to attempt to build it from source just to avoid confusion when my friends join my server.

Thanks!

**Comment by alexsocha** [comment]
In properties.txt, you can set showUpdateMessage=false
