### ISSUE TITLE
Failure on startup with forge 41.1.0 ("Needs language provider javafml:41.0.100 or above to load")

### ISSUE THREAD

**Issue by gkreitz** [alexsocha/luckyblock#90]
**Environment**
- Loader: Forge 41.1.0
- Mod version: 1.19-13.0
- OS: Windows

**Describe the bug**
Minecraft fails to start when the mod is present, showing an error message saying "Needs language provider javafml:41.0.100 or above to load". Bug is also mentioned in several comments on https://www.curseforge.com/minecraft/mc-mods/lucky-block 

I don't know anything about minecraft modding, but it seems like the javafml loader does not use semantic versioning, instead simply having the version set as `41`, even in forge `41.1`. Changing the line https://github.com/alexsocha/luckyblock/blob/854718555590b1650aa3a846bab08cfada4eca07/forge/src/main/resources/META-INF/mods.toml#L2 to read `loaderVersion="[41,)"` fixes the issue. Not submitting a PR as obviously you want to extract the major version from `${minForgeVersion}` rather than hard coding 41 and I'm not familiar enough with toml syntax to know how to do that.

**Screenshots**
If applicable, add screenshots here.

**Log file**
If applicable, add your log file here.

**Comment by alexsocha** [comment]
Thanks for looking into this! You're right, `javafml` used to have the same versioning scheme as forge, but now it's just a single number. I've fixed this in the `forge-1.19-13.2` release
