### ISSUE TITLE
Is there a way to use items from other mods in an addon's recipes.txt?

### ISSUE THREAD

**Issue by GuikiPT** [alexsocha/luckyblock#97]
Hello :)

I've been trying to create an addon so that it creates a new luckyblock.
To craft this new luckyblock I'm using items from other mods.

For some reason, items from other modes don't craft anything. But if i put the luckyblock (the normal one) in the middle of the craftable, the luckyblock that I'm making to craft appears.

My recipes.txt:
```
ppp,plp,ppp,i,pixelmon:poke_ball,l,lucky:lucky_block
```
![](https://cdn.discordapp.com/attachments/949320035594289234/1013498680956944545/unknown.png)

![](https://cdn.discordapp.com/attachments/949320035594289234/1013498733561913414/unknown.png)

**Comment by GuikiPT** [comment]
**Environment**
- **Loader:** Forge 14.23.5.2860
- **Mod version:** 1.12.0-2.0
- **OS:** Linux, also i tested on Windows to

**Comment by alexsocha** [comment]
Hi, I'd recommend using the JSON format for recipes: https://minecraft.fandom.com/wiki/Recipe#JSON_format. I've updated the template to make use of this instead of the legacy `recipes.txt`

**Comment by Brandonbr1** [comment]
> 

use:https://crafting.thedestruc7i0n.ca/ 
to make it even easier
thanks did not know that it supported json

**Comment by Brandonbr1** [comment]
@alexsocha does 1.16.5 support this JSON format
